# Generated by Django 3.2.8 on 2022-06-25 09:11

from django.db import migrations, models
import face_recog.models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(upload_to=face_recog.models.student.user_directory_path),
        ),
    ]
